# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import telemetry_pb2 as telemetry__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in telemetry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TelemetryServiceStub(object):
    """═══════════════════════════════════════════════
    Telemetry Service — Agent reports data to Server
    ═══════════════════════════════════════════════

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTelemetry = channel.stream_unary(
                '/voight.TelemetryService/StreamTelemetry',
                request_serializer=telemetry__pb2.TelemetryReport.SerializeToString,
                response_deserializer=telemetry__pb2.TelemetryAck.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/voight.TelemetryService/Heartbeat',
                request_serializer=telemetry__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=telemetry__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.RequestHelp = channel.unary_unary(
                '/voight.TelemetryService/RequestHelp',
                request_serializer=telemetry__pb2.HelpRequest.SerializeToString,
                response_deserializer=telemetry__pb2.HelpResponse.FromString,
                _registered_method=True)
        self.Disconnect = channel.unary_unary(
                '/voight.TelemetryService/Disconnect',
                request_serializer=telemetry__pb2.DisconnectRequest.SerializeToString,
                response_deserializer=telemetry__pb2.DisconnectResponse.FromString,
                _registered_method=True)


class TelemetryServiceServicer(object):
    """═══════════════════════════════════════════════
    Telemetry Service — Agent reports data to Server
    ═══════════════════════════════════════════════

    """

    def StreamTelemetry(self, request_iterator, context):
        """Stream telemetry data from agent to server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Send a single heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestHelp(self, request, context):
        """Contestant explicitly requests help from the Proctor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disconnect(self, request, context):
        """Contestant intentionally disconnects the agent (Graceful Exit)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelemetryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTelemetry': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=telemetry__pb2.TelemetryReport.FromString,
                    response_serializer=telemetry__pb2.TelemetryAck.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=telemetry__pb2.HeartbeatRequest.FromString,
                    response_serializer=telemetry__pb2.HeartbeatResponse.SerializeToString,
            ),
            'RequestHelp': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestHelp,
                    request_deserializer=telemetry__pb2.HelpRequest.FromString,
                    response_serializer=telemetry__pb2.HelpResponse.SerializeToString,
            ),
            'Disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.Disconnect,
                    request_deserializer=telemetry__pb2.DisconnectRequest.FromString,
                    response_serializer=telemetry__pb2.DisconnectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voight.TelemetryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voight.TelemetryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TelemetryService(object):
    """═══════════════════════════════════════════════
    Telemetry Service — Agent reports data to Server
    ═══════════════════════════════════════════════

    """

    @staticmethod
    def StreamTelemetry(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/voight.TelemetryService/StreamTelemetry',
            telemetry__pb2.TelemetryReport.SerializeToString,
            telemetry__pb2.TelemetryAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voight.TelemetryService/Heartbeat',
            telemetry__pb2.HeartbeatRequest.SerializeToString,
            telemetry__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestHelp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voight.TelemetryService/RequestHelp',
            telemetry__pb2.HelpRequest.SerializeToString,
            telemetry__pb2.HelpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voight.TelemetryService/Disconnect',
            telemetry__pb2.DisconnectRequest.SerializeToString,
            telemetry__pb2.DisconnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
