# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from voight import enrollment_pb2 as voight_dot_enrollment__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in voight/enrollment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EnrollmentServiceStub(object):
    """═══════════════════════════════════════════════
    Enrollment Service — Agent registers with Server
    ═══════════════════════════════════════════════

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enroll = channel.unary_unary(
                '/voight.EnrollmentService/Enroll',
                request_serializer=voight_dot_enrollment__pb2.EnrollmentRequest.SerializeToString,
                response_deserializer=voight_dot_enrollment__pb2.EnrollmentResponse.FromString,
                _registered_method=True)
        self.CheckStatus = channel.unary_unary(
                '/voight.EnrollmentService/CheckStatus',
                request_serializer=voight_dot_enrollment__pb2.StatusRequest.SerializeToString,
                response_deserializer=voight_dot_enrollment__pb2.StatusResponse.FromString,
                _registered_method=True)


class EnrollmentServiceServicer(object):
    """═══════════════════════════════════════════════
    Enrollment Service — Agent registers with Server
    ═══════════════════════════════════════════════

    """

    def Enroll(self, request, context):
        """Agent sends enrollment request with token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckStatus(self, request, context):
        """Agent checks if it's still enrolled and valid
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnrollmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Enroll': grpc.unary_unary_rpc_method_handler(
                    servicer.Enroll,
                    request_deserializer=voight_dot_enrollment__pb2.EnrollmentRequest.FromString,
                    response_serializer=voight_dot_enrollment__pb2.EnrollmentResponse.SerializeToString,
            ),
            'CheckStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckStatus,
                    request_deserializer=voight_dot_enrollment__pb2.StatusRequest.FromString,
                    response_serializer=voight_dot_enrollment__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voight.EnrollmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voight.EnrollmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnrollmentService(object):
    """═══════════════════════════════════════════════
    Enrollment Service — Agent registers with Server
    ═══════════════════════════════════════════════

    """

    @staticmethod
    def Enroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voight.EnrollmentService/Enroll',
            voight_dot_enrollment__pb2.EnrollmentRequest.SerializeToString,
            voight_dot_enrollment__pb2.EnrollmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voight.EnrollmentService/CheckStatus',
            voight_dot_enrollment__pb2.StatusRequest.SerializeToString,
            voight_dot_enrollment__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
