//go:build linux && ebpf

// ebpf_linux.go implements the eBPF kernel-level monitor for Linux.
// It loads BPF programs compiled by bpf2go and attaches them to kernel tracepoints
// for execve, connect, and openat syscalls.
//
// Requirements:
//   - Linux kernel >= 5.15 (BPF CO-RE support)
//   - Root or CAP_BPF + CAP_PERFMON capabilities
//   - Compiled BPF objects (generated by bpf2go — see generate.go)

package ebpf

import (
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"log"
	"net"
	"os"
	"strings"
	"time"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/perf"
	"github.com/cilium/ebpf/rlimit"
	"github.com/lockon/voight-agent/internal/config"
)

// EBPFMonitor manages eBPF program lifecycle and event processing.
type EBPFMonitor struct {
	cfg       *config.Config
	onExec    ExecCallback
	onConnect ConnectCallback
	onOpen    OpenCallback
	available bool
}

// New creates a new eBPF monitor with the provided callbacks.
func New(cfg *config.Config, onExec ExecCallback, onConnect ConnectCallback, onOpen OpenCallback) *EBPFMonitor {
	return &EBPFMonitor{
		cfg:       cfg,
		onExec:    onExec,
		onConnect: onConnect,
		onOpen:    onOpen,
	}
}

// IsAvailable checks if eBPF is supported on this system.
// Requires Linux >= 5.15 and appropriate capabilities.
func (m *EBPFMonitor) IsAvailable() bool {
	// Check kernel version >= 5.15
	major, minor := getKernelVersion()
	if major < 5 || (major == 5 && minor < 15) {
		log.Printf("[eBPF] Kernel %d.%d is below minimum 5.15 — eBPF disabled", major, minor)
		return false
	}

	// Check if we can access BPF subsystem
	// The actual availability is confirmed when we try to load programs in Run()
	m.available = true
	return true
}

// Run starts the eBPF monitoring loop.
func (m *EBPFMonitor) Run(ctx context.Context) {
	log.Println("[eBPF] Initializing kernel-level monitoring...")
	log.Println("[eBPF] Target tracepoints: sys_enter_execve, sys_enter_connect, sys_enter_openat")

	// Allow the current process to lock memory for eBPF resources.
	if err := rlimit.RemoveMemlock(); err != nil {
		log.Printf("[eBPF] Warning: Failed to remove memlock: %v", err)
	}

	// Load pre-compiled programs into the kernel.
	objs := bpfObjects{}
	if err := loadBpfObjects(&objs, nil); err != nil {
		log.Printf("[eBPF] Failed to load objects: %v", err)
		log.Println("[eBPF] NOTE: Did you run 'go generate' on a Linux machine?")
		return
	}
	defer objs.Close()

	// Attach tracepoints
	execLink, err := link.Tracepoint("syscalls", "sys_enter_execve", objs.TraceExecve, nil)
	if err != nil {
		log.Printf("[eBPF] Failed to attach execve tracepoint: %v", err)
		return
	}
	defer execLink.Close()

	connectLink, err := link.Tracepoint("syscalls", "sys_enter_connect", objs.TraceConnect, nil)
	if err != nil {
		log.Printf("[eBPF] Failed to attach connect tracepoint: %v", err)
		return
	}
	defer connectLink.Close()

	openLink, err := link.Tracepoint("syscalls", "sys_enter_openat", objs.TraceOpenat, nil)
	if err != nil {
		log.Printf("[eBPF] Failed to attach openat tracepoint: %v", err)
		return
	}
	defer openLink.Close()

	// Setup perf readers
	execRd, err := perf.NewReader(objs.ExecEvents, os.Getpagesize()*64)
	if err != nil {
		log.Printf("[eBPF] Failed to create exec perf reader: %v", err)
		return
	}
	defer execRd.Close()

	connectRd, err := perf.NewReader(objs.ConnectEvents, os.Getpagesize()*64)
	if err != nil {
		log.Printf("[eBPF] Failed to create connect perf reader: %v", err)
		return
	}
	defer connectRd.Close()

	openRd, err := perf.NewReader(objs.OpenEvents, os.Getpagesize()*64)
	if err != nil {
		log.Printf("[eBPF] Failed to create open perf reader: %v", err)
		return
	}
	defer openRd.Close()

	log.Println("[eBPF] Monitoring active.")

	// Start readers
	go m.readPerfEvents(ctx, execRd, m.processExecEvent)
	go m.readPerfEvents(ctx, connectRd, m.processConnectEvent)
	go m.readPerfEvents(ctx, openRd, m.processOpenEvent)

	// Block until context is cancelled
	<-ctx.Done()
	log.Println("[eBPF] Stopping.")
}

func (m *EBPFMonitor) readPerfEvents(ctx context.Context, rd *perf.Reader, processor func([]byte)) {
	// Close the reader when context is done to unblock rd.Read()
	go func() {
		<-ctx.Done()
		rd.Close()
	}()

	for {
		record, err := rd.Read()
		if err != nil {
			if ctx.Err() != nil {
				return // Context cancelled, exit normally
			}
			if errors.Is(err, perf.ErrClosed) {
				return
			}
			log.Printf("[eBPF] Error reading perf event: %v", err)
			continue
		}

		if record.LostSamples != 0 {
			log.Printf("[eBPF] Ring buffer full, dropped %d samples", record.LostSamples)
			continue
		}

		processor(record.RawSample)
	}
}

// processExecEvent handles a raw execve event from the BPF perf buffer.
func (m *EBPFMonitor) processExecEvent(data []byte) {
	if m.onExec == nil {
		return
	}

	var event bpfExecEvent
	if err := binary.Read(bytes.NewReader(data), binary.LittleEndian, &event); err != nil {
		return
	}

	comm := nullTermString(event.Comm[:])
	filename := nullTermString(event.Filename[:])
	m.onExec(int32(event.Pid), comm, filename, time.Now())
}

// processConnectEvent handles a raw connect event from the BPF perf buffer.
func (m *EBPFMonitor) processConnectEvent(data []byte) {
	if m.onConnect == nil {
		return
	}

	var event bpfConnectEvent
	if err := binary.Read(bytes.NewReader(data), binary.LittleEndian, &event); err != nil {
		return
	}

	comm := nullTermString(event.Comm[:])
	ip := uint32ToIP(event.Daddr)
	m.onConnect(int32(event.Pid), comm, ip, event.Dport, time.Now())
}

// processOpenEvent handles a raw openat event from the BPF perf buffer.
func (m *EBPFMonitor) processOpenEvent(data []byte) {
	if m.onOpen == nil {
		return
	}

	var event bpfOpenEvent
	if err := binary.Read(bytes.NewReader(data), binary.LittleEndian, &event); err != nil {
		return
	}

	comm := nullTermString(event.Comm[:])
	filename := nullTermString(event.Filename[:])
	m.onOpen(int32(event.Pid), comm, filename, time.Now())
}

// --- Helpers ---

// nullTermString converts a null-terminated byte array to a Go string.
func nullTermString(b []byte) string {
	n := bytes.IndexByte(b, 0)
	if n < 0 {
		n = len(b)
	}
	return string(b[:n])
}

// uint32ToIP converts a network byte order uint32 to an IP string.
func uint32ToIP(addr uint32) string {
	ip := make(net.IP, 4)
	binary.BigEndian.PutUint32(ip, addr)
	return ip.String()
}

// getKernelVersion reads the kernel version from /proc/version.
func getKernelVersion() (major, minor int) {
	data, err := os.ReadFile("/proc/version")
	if err != nil {
		return 0, 0
	}

	// Format: "Linux version 5.15.0-100-generic ..."
	version := string(data)
	parts := strings.Fields(version)
	if len(parts) < 3 {
		return 0, 0
	}

	versionStr := parts[2] // "5.15.0-100-generic"
	fmt.Sscanf(versionStr, "%d.%d", &major, &minor)
	return major, minor
}
