"""Add scan_interval

Revision ID: 4ce9bd98529c
Revises: b46c4fa79d15
Create Date: 2026-05-03 08:38:39.973101+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce9bd98529c'
down_revision: Union[str, None] = 'b46c4fa79d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_policy', sa.Column('scan_interval', sa.Integer(), nullable=False, server_default='5'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_policy', 'scan_interval')
    # ### end Alembic commands ###
