"""Add join_code

Revision ID: 3d325ab1e1ce
Revises: 4ce9bd98529c
Create Date: 2026-05-31 11:10:09.956719+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d325ab1e1ce'
down_revision: Union[str, None] = '4ce9bd98529c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('join_code', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_competitions_join_code'), 'competitions', ['join_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitions_join_code'), table_name='competitions')
    op.drop_column('competitions', 'join_code')
    # ### end Alembic commands ###
