"""Add screen_lock_count

Revision ID: b46c4fa79d15
Revises: e017ebc4b8c7
Create Date: 2026-05-02 15:38:55.826204+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b46c4fa79d15'
down_revision: Union[str, None] = 'e017ebc4b8c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contestants', sa.Column('screen_lock_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contestants', 'screen_lock_count')
    # ### end Alembic commands ###
