"""Add banner column to Competition

Revision ID: 15ceba36b77b
Revises: 85b2df0e1acc
Create Date: 2026-05-01 09:58:59.361726+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ceba36b77b'
down_revision: Union[str, None] = '85b2df0e1acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('banner', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'banner')
    # ### end Alembic commands ###
