"""add system policy

Revision ID: e017ebc4b8c7
Revises: 15ceba36b77b
Create Date: 2026-05-01 11:53:50.561528+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e017ebc4b8c7'
down_revision: Union[str, None] = '15ceba36b77b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domains', sa.JSON(), nullable=False),
    sa.Column('processes', sa.JSON(), nullable=False),
    sa.Column('extensions', sa.JSON(), nullable=False),
    sa.Column('min_file_size_mb', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_policy')
    # ### end Alembic commands ###
