"""Initial

Revision ID: 85b2df0e1acc
Revises: 
Create Date: 2026-04-30 16:35:36.860242+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b2df0e1acc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proctors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('contestants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competition_id', sa.UUID(), nullable=False),
    sa.Column('handle', sa.String(length=100), nullable=False),
    sa.Column('team', sa.String(length=100), nullable=True),
    sa.Column('enrollment_token', sa.String(length=255), nullable=True),
    sa.Column('agent_fingerprint', sa.String(length=512), nullable=True),
    sa.Column('agent_version', sa.String(length=50), nullable=True),
    sa.Column('is_enrolled', sa.Boolean(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_token')
    )
    op.create_index('ix_contestants_competition_id', 'contestants', ['competition_id'], unique=False)
    op.create_index('ix_contestants_enrollment_token', 'contestants', ['enrollment_token'], unique=False)
    op.create_table('heartbeats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contestant_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('agent_version', sa.String(length=50), nullable=True),
    sa.Column('agent_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['contestant_id'], ['contestants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_heartbeats_contestant_ts', 'heartbeats', ['contestant_id', 'ts'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contestant_id', sa.UUID(), nullable=False),
    sa.Column('indicator_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contestant_id'], ['contestants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_contestant_id', 'incidents', ['contestant_id'], unique=False)
    op.create_index('ix_incidents_detected_at', 'incidents', ['detected_at'], unique=False)
    op.create_index('ix_incidents_status', 'incidents', ['status'], unique=False)
    op.create_table('integrity_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contestant_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contestant_id'], ['contestants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_integrity_scores_calculated_at', 'integrity_scores', ['calculated_at'], unique=False)
    op.create_index('ix_integrity_scores_contestant_id', 'integrity_scores', ['contestant_id'], unique=False)
    op.create_table('network_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contestant_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dst_domain', sa.String(length=255), nullable=True),
    sa.Column('dst_ip', sa.String(length=45), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['contestant_id'], ['contestants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_network_logs_contestant_ts', 'network_logs', ['contestant_id', 'ts'], unique=False)
    op.create_table('process_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contestant_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('process_name', sa.String(length=255), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('cmdline', sa.Text(), nullable=True),
    sa.Column('cpu_pct', sa.Float(), nullable=True),
    sa.Column('mem_mb', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['contestant_id'], ['contestants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_process_logs_contestant_ts', 'process_logs', ['contestant_id', 'ts'], unique=False)
    op.create_table('resource_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contestant_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cpu_pct', sa.Float(), nullable=True),
    sa.Column('ram_pct', sa.Float(), nullable=True),
    sa.Column('gpu_pct', sa.Float(), nullable=True),
    sa.Column('vram_mb', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['contestant_id'], ['contestants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resource_snapshots_contestant_ts', 'resource_snapshots', ['contestant_id', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resource_snapshots_contestant_ts', table_name='resource_snapshots')
    op.drop_table('resource_snapshots')
    op.drop_index('ix_process_logs_contestant_ts', table_name='process_logs')
    op.drop_table('process_logs')
    op.drop_index('ix_network_logs_contestant_ts', table_name='network_logs')
    op.drop_table('network_logs')
    op.drop_index('ix_integrity_scores_contestant_id', table_name='integrity_scores')
    op.drop_index('ix_integrity_scores_calculated_at', table_name='integrity_scores')
    op.drop_table('integrity_scores')
    op.drop_index('ix_incidents_status', table_name='incidents')
    op.drop_index('ix_incidents_detected_at', table_name='incidents')
    op.drop_index('ix_incidents_contestant_id', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_heartbeats_contestant_ts', table_name='heartbeats')
    op.drop_table('heartbeats')
    op.drop_index('ix_contestants_enrollment_token', table_name='contestants')
    op.drop_index('ix_contestants_competition_id', table_name='contestants')
    op.drop_table('contestants')
    op.drop_table('proctors')
    op.drop_table('competitions')
    # ### end Alembic commands ###
