// LOCKON VOIGHT — Enrollment Protocol Buffer Definition
// Defines the gRPC service for Agent enrollment with the Server.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: voight/enrollment.proto

package voight

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollmentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentToken string                 `protobuf:"bytes,1,opt,name=enrollment_token,json=enrollmentToken,proto3" json:"enrollment_token,omitempty"` // Token provided by proctor (used as payload)
	Fingerprint     *MachineFingerprint    `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`                                // Hardware fingerprint of contestant machine
	AgentVersion    string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	AgentBinaryHash string                 `protobuf:"bytes,4,opt,name=agent_binary_hash,json=agentBinaryHash,proto3" json:"agent_binary_hash,omitempty"` // SHA-256 of agent binary
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrollmentRequest) Reset() {
	*x = EnrollmentRequest{}
	mi := &file_voight_enrollment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentRequest) ProtoMessage() {}

func (x *EnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voight_enrollment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentRequest.ProtoReflect.Descriptor instead.
func (*EnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_voight_enrollment_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollmentRequest) GetEnrollmentToken() string {
	if x != nil {
		return x.EnrollmentToken
	}
	return ""
}

func (x *EnrollmentRequest) GetFingerprint() *MachineFingerprint {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

func (x *EnrollmentRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *EnrollmentRequest) GetAgentBinaryHash() string {
	if x != nil {
		return x.AgentBinaryHash
	}
	return ""
}

type EnrollmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                   // Assigned unique agent ID
	ContestantId  string                 `protobuf:"bytes,4,opt,name=contestant_id,json=contestantId,proto3" json:"contestant_id,omitempty"`    // Linked contestant UUID
	CompetitionId string                 `protobuf:"bytes,5,opt,name=competition_id,json=competitionId,proto3" json:"competition_id,omitempty"` // Linked competition UUID
	Config        *AgentConfiguration    `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`                                    // Initial configuration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollmentResponse) Reset() {
	*x = EnrollmentResponse{}
	mi := &file_voight_enrollment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentResponse) ProtoMessage() {}

func (x *EnrollmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voight_enrollment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentResponse.ProtoReflect.Descriptor instead.
func (*EnrollmentResponse) Descriptor() ([]byte, []int) {
	return file_voight_enrollment_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnrollmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EnrollmentResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EnrollmentResponse) GetContestantId() string {
	if x != nil {
		return x.ContestantId
	}
	return ""
}

func (x *EnrollmentResponse) GetCompetitionId() string {
	if x != nil {
		return x.CompetitionId
	}
	return ""
}

func (x *EnrollmentResponse) GetConfig() *AgentConfiguration {
	if x != nil {
		return x.Config
	}
	return nil
}

type MachineFingerprint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"` // windows, linux, darwin
	OsVersion     string                 `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Architecture  string                 `protobuf:"bytes,4,opt,name=architecture,proto3" json:"architecture,omitempty"` // amd64, arm64
	CpuCores      int32                  `protobuf:"varint,5,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	TotalRamMb    int64                  `protobuf:"varint,6,opt,name=total_ram_mb,json=totalRamMb,proto3" json:"total_ram_mb,omitempty"`
	GpuName       string                 `protobuf:"bytes,7,opt,name=gpu_name,json=gpuName,proto3" json:"gpu_name,omitempty"`
	GpuVramMb     int64                  `protobuf:"varint,8,opt,name=gpu_vram_mb,json=gpuVramMb,proto3" json:"gpu_vram_mb,omitempty"`
	MacAddress    string                 `protobuf:"bytes,9,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"` // Primary NIC MAC
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineFingerprint) Reset() {
	*x = MachineFingerprint{}
	mi := &file_voight_enrollment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineFingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineFingerprint) ProtoMessage() {}

func (x *MachineFingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_voight_enrollment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineFingerprint.ProtoReflect.Descriptor instead.
func (*MachineFingerprint) Descriptor() ([]byte, []int) {
	return file_voight_enrollment_proto_rawDescGZIP(), []int{2}
}

func (x *MachineFingerprint) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MachineFingerprint) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *MachineFingerprint) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *MachineFingerprint) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *MachineFingerprint) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *MachineFingerprint) GetTotalRamMb() int64 {
	if x != nil {
		return x.TotalRamMb
	}
	return 0
}

func (x *MachineFingerprint) GetGpuName() string {
	if x != nil {
		return x.GpuName
	}
	return ""
}

func (x *MachineFingerprint) GetGpuVramMb() int64 {
	if x != nil {
		return x.GpuVramMb
	}
	return 0
}

func (x *MachineFingerprint) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

type AgentConfiguration struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatIntervalSeconds    int32                  `protobuf:"varint,1,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	ProcessScanIntervalSeconds  int32                  `protobuf:"varint,2,opt,name=process_scan_interval_seconds,json=processScanIntervalSeconds,proto3" json:"process_scan_interval_seconds,omitempty"`
	NetworkScanIntervalSeconds  int32                  `protobuf:"varint,3,opt,name=network_scan_interval_seconds,json=networkScanIntervalSeconds,proto3" json:"network_scan_interval_seconds,omitempty"`
	ResourceScanIntervalSeconds int32                  `protobuf:"varint,4,opt,name=resource_scan_interval_seconds,json=resourceScanIntervalSeconds,proto3" json:"resource_scan_interval_seconds,omitempty"`
	// Detection rules
	AiProcessNames      []string `protobuf:"bytes,10,rep,name=ai_process_names,json=aiProcessNames,proto3" json:"ai_process_names,omitempty"`                // Process names to flag
	AiDomains           []string `protobuf:"bytes,11,rep,name=ai_domains,json=aiDomains,proto3" json:"ai_domains,omitempty"`                                 // Domains to flag
	ModelFileExtensions []string `protobuf:"bytes,12,rep,name=model_file_extensions,json=modelFileExtensions,proto3" json:"model_file_extensions,omitempty"` // File extensions to scan
	// Server endpoints
	TelemetryEndpoint string `protobuf:"bytes,20,opt,name=telemetry_endpoint,json=telemetryEndpoint,proto3" json:"telemetry_endpoint,omitempty"`
	HeartbeatEndpoint string `protobuf:"bytes,21,opt,name=heartbeat_endpoint,json=heartbeatEndpoint,proto3" json:"heartbeat_endpoint,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AgentConfiguration) Reset() {
	*x = AgentConfiguration{}
	mi := &file_voight_enrollment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfiguration) ProtoMessage() {}

func (x *AgentConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_voight_enrollment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfiguration.ProtoReflect.Descriptor instead.
func (*AgentConfiguration) Descriptor() ([]byte, []int) {
	return file_voight_enrollment_proto_rawDescGZIP(), []int{3}
}

func (x *AgentConfiguration) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *AgentConfiguration) GetProcessScanIntervalSeconds() int32 {
	if x != nil {
		return x.ProcessScanIntervalSeconds
	}
	return 0
}

func (x *AgentConfiguration) GetNetworkScanIntervalSeconds() int32 {
	if x != nil {
		return x.NetworkScanIntervalSeconds
	}
	return 0
}

func (x *AgentConfiguration) GetResourceScanIntervalSeconds() int32 {
	if x != nil {
		return x.ResourceScanIntervalSeconds
	}
	return 0
}

func (x *AgentConfiguration) GetAiProcessNames() []string {
	if x != nil {
		return x.AiProcessNames
	}
	return nil
}

func (x *AgentConfiguration) GetAiDomains() []string {
	if x != nil {
		return x.AiDomains
	}
	return nil
}

func (x *AgentConfiguration) GetModelFileExtensions() []string {
	if x != nil {
		return x.ModelFileExtensions
	}
	return nil
}

func (x *AgentConfiguration) GetTelemetryEndpoint() string {
	if x != nil {
		return x.TelemetryEndpoint
	}
	return ""
}

func (x *AgentConfiguration) GetHeartbeatEndpoint() string {
	if x != nil {
		return x.HeartbeatEndpoint
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ContestantId  string                 `protobuf:"bytes,2,opt,name=contestant_id,json=contestantId,proto3" json:"contestant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_voight_enrollment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voight_enrollment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_voight_enrollment_proto_rawDescGZIP(), []int{4}
}

func (x *StatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StatusRequest) GetContestantId() string {
	if x != nil {
		return x.ContestantId
	}
	return ""
}

type StatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Enrolled          bool                   `protobuf:"varint,1,opt,name=enrolled,proto3" json:"enrolled,omitempty"`
	Active            bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`                                               // Competition is still active
	CompetitionStatus string                 `protobuf:"bytes,3,opt,name=competition_status,json=competitionStatus,proto3" json:"competition_status,omitempty"` // draft, active, completed
	Message           string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_voight_enrollment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voight_enrollment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_voight_enrollment_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetEnrolled() bool {
	if x != nil {
		return x.Enrolled
	}
	return false
}

func (x *StatusResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *StatusResponse) GetCompetitionStatus() string {
	if x != nil {
		return x.CompetitionStatus
	}
	return ""
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_voight_enrollment_proto protoreflect.FileDescriptor

const file_voight_enrollment_proto_rawDesc = "" +
	"\n" +
	"\x17voight/enrollment.proto\x12\x06voight\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcd\x01\n" +
	"\x11EnrollmentRequest\x12)\n" +
	"\x10enrollment_token\x18\x01 \x01(\tR\x0fenrollmentToken\x12<\n" +
	"\vfingerprint\x18\x02 \x01(\v2\x1a.voight.MachineFingerprintR\vfingerprint\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12*\n" +
	"\x11agent_binary_hash\x18\x04 \x01(\tR\x0fagentBinaryHash\"\xe3\x01\n" +
	"\x12EnrollmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12#\n" +
	"\rcontestant_id\x18\x04 \x01(\tR\fcontestantId\x12%\n" +
	"\x0ecompetition_id\x18\x05 \x01(\tR\rcompetitionId\x122\n" +
	"\x06config\x18\x06 \x01(\v2\x1a.voight.AgentConfigurationR\x06config\"\x9e\x02\n" +
	"\x12MachineFingerprint\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x03 \x01(\tR\tosVersion\x12\"\n" +
	"\farchitecture\x18\x04 \x01(\tR\farchitecture\x12\x1b\n" +
	"\tcpu_cores\x18\x05 \x01(\x05R\bcpuCores\x12 \n" +
	"\ftotal_ram_mb\x18\x06 \x01(\x03R\n" +
	"totalRamMb\x12\x19\n" +
	"\bgpu_name\x18\a \x01(\tR\agpuName\x12\x1e\n" +
	"\vgpu_vram_mb\x18\b \x01(\x03R\tgpuVramMb\x12\x1f\n" +
	"\vmac_address\x18\t \x01(\tR\n" +
	"macAddress\"\xf8\x03\n" +
	"\x12AgentConfiguration\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x01 \x01(\x05R\x18heartbeatIntervalSeconds\x12A\n" +
	"\x1dprocess_scan_interval_seconds\x18\x02 \x01(\x05R\x1aprocessScanIntervalSeconds\x12A\n" +
	"\x1dnetwork_scan_interval_seconds\x18\x03 \x01(\x05R\x1anetworkScanIntervalSeconds\x12C\n" +
	"\x1eresource_scan_interval_seconds\x18\x04 \x01(\x05R\x1bresourceScanIntervalSeconds\x12(\n" +
	"\x10ai_process_names\x18\n" +
	" \x03(\tR\x0eaiProcessNames\x12\x1d\n" +
	"\n" +
	"ai_domains\x18\v \x03(\tR\taiDomains\x122\n" +
	"\x15model_file_extensions\x18\f \x03(\tR\x13modelFileExtensions\x12-\n" +
	"\x12telemetry_endpoint\x18\x14 \x01(\tR\x11telemetryEndpoint\x12-\n" +
	"\x12heartbeat_endpoint\x18\x15 \x01(\tR\x11heartbeatEndpoint\"O\n" +
	"\rStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\rcontestant_id\x18\x02 \x01(\tR\fcontestantId\"\x8d\x01\n" +
	"\x0eStatusResponse\x12\x1a\n" +
	"\benrolled\x18\x01 \x01(\bR\benrolled\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12-\n" +
	"\x12competition_status\x18\x03 \x01(\tR\x11competitionStatus\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2\x92\x01\n" +
	"\x11EnrollmentService\x12?\n" +
	"\x06Enroll\x12\x19.voight.EnrollmentRequest\x1a\x1a.voight.EnrollmentResponse\x12<\n" +
	"\vCheckStatus\x12\x15.voight.StatusRequest\x1a\x16.voight.StatusResponseB-Z+github.com/lockon/voight-agent/proto/voightb\x06proto3"

var (
	file_voight_enrollment_proto_rawDescOnce sync.Once
	file_voight_enrollment_proto_rawDescData []byte
)

func file_voight_enrollment_proto_rawDescGZIP() []byte {
	file_voight_enrollment_proto_rawDescOnce.Do(func() {
		file_voight_enrollment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_voight_enrollment_proto_rawDesc), len(file_voight_enrollment_proto_rawDesc)))
	})
	return file_voight_enrollment_proto_rawDescData
}

var file_voight_enrollment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_voight_enrollment_proto_goTypes = []any{
	(*EnrollmentRequest)(nil),  // 0: voight.EnrollmentRequest
	(*EnrollmentResponse)(nil), // 1: voight.EnrollmentResponse
	(*MachineFingerprint)(nil), // 2: voight.MachineFingerprint
	(*AgentConfiguration)(nil), // 3: voight.AgentConfiguration
	(*StatusRequest)(nil),      // 4: voight.StatusRequest
	(*StatusResponse)(nil),     // 5: voight.StatusResponse
}
var file_voight_enrollment_proto_depIdxs = []int32{
	2, // 0: voight.EnrollmentRequest.fingerprint:type_name -> voight.MachineFingerprint
	3, // 1: voight.EnrollmentResponse.config:type_name -> voight.AgentConfiguration
	0, // 2: voight.EnrollmentService.Enroll:input_type -> voight.EnrollmentRequest
	4, // 3: voight.EnrollmentService.CheckStatus:input_type -> voight.StatusRequest
	1, // 4: voight.EnrollmentService.Enroll:output_type -> voight.EnrollmentResponse
	5, // 5: voight.EnrollmentService.CheckStatus:output_type -> voight.StatusResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_voight_enrollment_proto_init() }
func file_voight_enrollment_proto_init() {
	if File_voight_enrollment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_voight_enrollment_proto_rawDesc), len(file_voight_enrollment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_voight_enrollment_proto_goTypes,
		DependencyIndexes: file_voight_enrollment_proto_depIdxs,
		MessageInfos:      file_voight_enrollment_proto_msgTypes,
	}.Build()
	File_voight_enrollment_proto = out.File
	file_voight_enrollment_proto_goTypes = nil
	file_voight_enrollment_proto_depIdxs = nil
}
