// LOCKON VOIGHT — Telemetry Protocol Buffer Definition
// Defines the data structures and gRPC service for Agent → Server communication.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: voight/telemetry.proto

package voight

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryReport struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AgentId      string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ContestantId string                 `protobuf:"bytes,2,opt,name=contestant_id,json=contestantId,proto3" json:"contestant_id,omitempty"`
	Timestamp    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// One of the following will be populated per report
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*TelemetryReport_ProcessSnapshot
	//	*TelemetryReport_NetworkEvent
	//	*TelemetryReport_ResourceSnapshot
	//	*TelemetryReport_FileAlert
	Payload       isTelemetryReport_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryReport) Reset() {
	*x = TelemetryReport{}
	mi := &file_voight_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryReport) ProtoMessage() {}

func (x *TelemetryReport) ProtoReflect() protoreflect.Message {
	mi := &file_voight_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryReport.ProtoReflect.Descriptor instead.
func (*TelemetryReport) Descriptor() ([]byte, []int) {
	return file_voight_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TelemetryReport) GetContestantId() string {
	if x != nil {
		return x.ContestantId
	}
	return ""
}

func (x *TelemetryReport) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TelemetryReport) GetPayload() isTelemetryReport_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TelemetryReport) GetProcessSnapshot() *ProcessSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryReport_ProcessSnapshot); ok {
			return x.ProcessSnapshot
		}
	}
	return nil
}

func (x *TelemetryReport) GetNetworkEvent() *NetworkEvent {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryReport_NetworkEvent); ok {
			return x.NetworkEvent
		}
	}
	return nil
}

func (x *TelemetryReport) GetResourceSnapshot() *ResourceSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryReport_ResourceSnapshot); ok {
			return x.ResourceSnapshot
		}
	}
	return nil
}

func (x *TelemetryReport) GetFileAlert() *FileAlert {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryReport_FileAlert); ok {
			return x.FileAlert
		}
	}
	return nil
}

type isTelemetryReport_Payload interface {
	isTelemetryReport_Payload()
}

type TelemetryReport_ProcessSnapshot struct {
	ProcessSnapshot *ProcessSnapshot `protobuf:"bytes,10,opt,name=process_snapshot,json=processSnapshot,proto3,oneof"`
}

type TelemetryReport_NetworkEvent struct {
	NetworkEvent *NetworkEvent `protobuf:"bytes,11,opt,name=network_event,json=networkEvent,proto3,oneof"`
}

type TelemetryReport_ResourceSnapshot struct {
	ResourceSnapshot *ResourceSnapshot `protobuf:"bytes,12,opt,name=resource_snapshot,json=resourceSnapshot,proto3,oneof"`
}

type TelemetryReport_FileAlert struct {
	FileAlert *FileAlert `protobuf:"bytes,13,opt,name=file_alert,json=fileAlert,proto3,oneof"`
}

func (*TelemetryReport_ProcessSnapshot) isTelemetryReport_Payload() {}

func (*TelemetryReport_NetworkEvent) isTelemetryReport_Payload() {}

func (*TelemetryReport_ResourceSnapshot) isTelemetryReport_Payload() {}

func (*TelemetryReport_FileAlert) isTelemetryReport_Payload() {}

type TelemetryAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	EventsReceived int32                  `protobuf:"varint,3,opt,name=events_received,json=eventsReceived,proto3" json:"events_received,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TelemetryAck) Reset() {
	*x = TelemetryAck{}
	mi := &file_voight_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryAck) ProtoMessage() {}

func (x *TelemetryAck) ProtoReflect() protoreflect.Message {
	mi := &file_voight_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryAck.ProtoReflect.Descriptor instead.
func (*TelemetryAck) Descriptor() ([]byte, []int) {
	return file_voight_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TelemetryAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TelemetryAck) GetEventsReceived() int32 {
	if x != nil {
		return x.EventsReceived
	}
	return 0
}

type ProcessSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*ProcessInfo         `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessSnapshot) Reset() {
	*x = ProcessSnapshot{}
	mi := &file_voight_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessSnapshot) ProtoMessage() {}

func (x *ProcessSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_voight_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessSnapshot.ProtoReflect.Descriptor instead.
func (*ProcessSnapshot) Descriptor() ([]byte, []int) {
	return file_voight_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessSnapshot) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

type ProcessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Cmdline       string                 `protobuf:"bytes,3,opt,name=cmdline,proto3" json:"cmdline,omitempty"`
	CpuPercent    float32                `protobuf:"fixed32,4,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryMb      float32                `protobuf:"fixed32,5,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"` // AI_EDITOR, LOCAL_LLM, AI_AGENT, NORMAL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_voight_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_voight_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_voight_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetCmdline() string {
	if x != nil {
		return x.Cmdline
	}
	return ""
}

func (x *ProcessInfo) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessInfo) GetMemoryMb() float32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *ProcessInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type NetworkEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DstDomain     string                 `protobuf:"bytes,1,opt,name=dst_domain,json=dstDomain,proto3" json:"dst_domain,omitempty"`
	DstIp         string                 `protobuf:"bytes,2,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	DstPort       int32                  `protobuf:"varint,3,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"` // TCP, UDP, DNS
	Verdict       string                 `protobuf:"bytes,5,opt,name=verdict,proto3" json:"verdict,omitempty"`   // AI_SERVICE, SAFE, UNKNOWN
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkEvent) Reset() {
	*x = NetworkEvent{}
	mi := &file_voight_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEvent) ProtoMessage() {}

func (x *NetworkEvent) ProtoReflect() protoreflect.Message {
	mi := &file_voight_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEvent.ProtoReflect.Descriptor instead.
func (*NetworkEvent) Descriptor() ([]byte, []int) {
	return file_voight_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkEvent) GetDstDomain() string {
	if x != nil {
		return x.DstDomain
	}
	return ""
}

func (x *NetworkEvent) GetDstIp() string {
	if x != nil {
		return x.DstIp
	}
	return ""
}

func (x *NetworkEvent) GetDstPort() int32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *NetworkEvent) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NetworkEvent) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

type ResourceSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float32                `protobuf:"fixed32,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	RamPercent    float32                `protobuf:"fixed32,2,opt,name=ram_percent,json=ramPercent,proto3" json:"ram_percent,omitempty"`
	GpuPercent    float32                `protobuf:"fixed32,3,opt,name=gpu_percent,json=gpuPercent,proto3" json:"gpu_percent,omitempty"`
	VramMb        float32                `protobuf:"fixed32,4,opt,name=vram_mb,json=vramMb,proto3" json:"vram_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSnapshot) Reset() {
	*x = ResourceSnapshot{}
	mi := &file_voight_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSnapshot) ProtoMessage() {}

func (x *ResourceSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_voight_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSnapshot.ProtoReflect.Descriptor instead.
func (*ResourceSnapshot) Descriptor() ([]byte, []int) {
	return file_voight_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceSnapshot) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ResourceSnapshot) GetRamPercent() float32 {
	if x != nil {
		return x.RamPercent
	}
	return 0
}

func (x *ResourceSnapshot) GetGpuPercent() float32 {
	if x != nil {
		return x.GpuPercent
	}
	return 0
}

func (x *ResourceSnapshot) GetVramMb() float32 {
	if x != nil {
		return x.VramMb
	}
	return 0
}

type FileAlert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSizeBytes int64                  `protobuf:"varint,3,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	FileType      string                 `protobuf:"bytes,4,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"` // GGUF, SAFETENSORS, BIN
	HashSha256    string                 `protobuf:"bytes,5,opt,name=hash_sha256,json=hashSha256,proto3" json:"hash_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileAlert) Reset() {
	*x = FileAlert{}
	mi := &file_voight_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileAlert) ProtoMessage() {}

func (x *FileAlert) ProtoReflect() protoreflect.Message {
	mi := &file_voight_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileAlert.ProtoReflect.Descriptor instead.
func (*FileAlert) Descriptor() ([]byte, []int) {
	return file_voight_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *FileAlert) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileAlert) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileAlert) GetFileSizeBytes() int64 {
	if x != nil {
		return x.FileSizeBytes
	}
	return 0
}

func (x *FileAlert) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *FileAlert) GetHashSha256() string {
	if x != nil {
		return x.HashSha256
	}
	return ""
}

type HeartbeatRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ContestantId    string                 `protobuf:"bytes,2,opt,name=contestant_id,json=contestantId,proto3" json:"contestant_id,omitempty"`
	AgentVersion    string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	AgentBinaryHash string                 `protobuf:"bytes,4,opt,name=agent_binary_hash,json=agentBinaryHash,proto3" json:"agent_binary_hash,omitempty"` // SHA-256 of the running binary
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_voight_telemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voight_telemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_voight_telemetry_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetContestantId() string {
	if x != nil {
		return x.ContestantId
	}
	return ""
}

func (x *HeartbeatRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *HeartbeatRequest) GetAgentBinaryHash() string {
	if x != nil {
		return x.AgentBinaryHash
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type HeartbeatResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged             bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	HeartbeatIntervalSeconds int32                  `protobuf:"varint,2,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"` // Server can adjust interval
	ConfigUpdate             *AgentConfig           `protobuf:"bytes,3,opt,name=config_update,json=configUpdate,proto3" json:"config_update,omitempty"`                                        // Optional config push
	DeployWarningPayload     bool                   `protobuf:"varint,4,opt,name=deploy_warning_payload,json=deployWarningPayload,proto3" json:"deploy_warning_payload,omitempty"`             // Command to lock screen
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_voight_telemetry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voight_telemetry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_voight_telemetry_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *HeartbeatResponse) GetConfigUpdate() *AgentConfig {
	if x != nil {
		return x.ConfigUpdate
	}
	return nil
}

func (x *HeartbeatResponse) GetDeployWarningPayload() bool {
	if x != nil {
		return x.DeployWarningPayload
	}
	return false
}

type AgentConfig struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	ProcessScanIntervalSeconds  int32                  `protobuf:"varint,1,opt,name=process_scan_interval_seconds,json=processScanIntervalSeconds,proto3" json:"process_scan_interval_seconds,omitempty"`
	NetworkScanIntervalSeconds  int32                  `protobuf:"varint,2,opt,name=network_scan_interval_seconds,json=networkScanIntervalSeconds,proto3" json:"network_scan_interval_seconds,omitempty"`
	ResourceScanIntervalSeconds int32                  `protobuf:"varint,3,opt,name=resource_scan_interval_seconds,json=resourceScanIntervalSeconds,proto3" json:"resource_scan_interval_seconds,omitempty"`
	AdditionalAiDomains         []string               `protobuf:"bytes,4,rep,name=additional_ai_domains,json=additionalAiDomains,proto3" json:"additional_ai_domains,omitempty"`       // Extra domains to watch
	AdditionalAiProcesses       []string               `protobuf:"bytes,5,rep,name=additional_ai_processes,json=additionalAiProcesses,proto3" json:"additional_ai_processes,omitempty"` // Extra process names to flag
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_voight_telemetry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_voight_telemetry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_voight_telemetry_proto_rawDescGZIP(), []int{9}
}

func (x *AgentConfig) GetProcessScanIntervalSeconds() int32 {
	if x != nil {
		return x.ProcessScanIntervalSeconds
	}
	return 0
}

func (x *AgentConfig) GetNetworkScanIntervalSeconds() int32 {
	if x != nil {
		return x.NetworkScanIntervalSeconds
	}
	return 0
}

func (x *AgentConfig) GetResourceScanIntervalSeconds() int32 {
	if x != nil {
		return x.ResourceScanIntervalSeconds
	}
	return 0
}

func (x *AgentConfig) GetAdditionalAiDomains() []string {
	if x != nil {
		return x.AdditionalAiDomains
	}
	return nil
}

func (x *AgentConfig) GetAdditionalAiProcesses() []string {
	if x != nil {
		return x.AdditionalAiProcesses
	}
	return nil
}

var File_voight_telemetry_proto protoreflect.FileDescriptor

const file_voight_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x16voight/telemetry.proto\x12\x06voight\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x03\n" +
	"\x0fTelemetryReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\rcontestant_id\x18\x02 \x01(\tR\fcontestantId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12D\n" +
	"\x10process_snapshot\x18\n" +
	" \x01(\v2\x17.voight.ProcessSnapshotH\x00R\x0fprocessSnapshot\x12;\n" +
	"\rnetwork_event\x18\v \x01(\v2\x14.voight.NetworkEventH\x00R\fnetworkEvent\x12G\n" +
	"\x11resource_snapshot\x18\f \x01(\v2\x18.voight.ResourceSnapshotH\x00R\x10resourceSnapshot\x122\n" +
	"\n" +
	"file_alert\x18\r \x01(\v2\x11.voight.FileAlertH\x00R\tfileAlertB\t\n" +
	"\apayload\"k\n" +
	"\fTelemetryAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fevents_received\x18\x03 \x01(\x05R\x0eeventsReceived\"D\n" +
	"\x0fProcessSnapshot\x121\n" +
	"\tprocesses\x18\x01 \x03(\v2\x13.voight.ProcessInfoR\tprocesses\"\xa7\x01\n" +
	"\vProcessInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x18\n" +
	"\acmdline\x18\x03 \x01(\tR\acmdline\x12\x1f\n" +
	"\vcpu_percent\x18\x04 \x01(\x02R\n" +
	"cpuPercent\x12\x1b\n" +
	"\tmemory_mb\x18\x05 \x01(\x02R\bmemoryMb\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\"\x95\x01\n" +
	"\fNetworkEvent\x12\x1d\n" +
	"\n" +
	"dst_domain\x18\x01 \x01(\tR\tdstDomain\x12\x15\n" +
	"\x06dst_ip\x18\x02 \x01(\tR\x05dstIp\x12\x19\n" +
	"\bdst_port\x18\x03 \x01(\x05R\adstPort\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x18\n" +
	"\averdict\x18\x05 \x01(\tR\averdict\"\x8e\x01\n" +
	"\x10ResourceSnapshot\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x02R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vram_percent\x18\x02 \x01(\x02R\n" +
	"ramPercent\x12\x1f\n" +
	"\vgpu_percent\x18\x03 \x01(\x02R\n" +
	"gpuPercent\x12\x17\n" +
	"\avram_mb\x18\x04 \x01(\x02R\x06vramMb\"\xab\x01\n" +
	"\tFileAlert\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12&\n" +
	"\x0ffile_size_bytes\x18\x03 \x01(\x03R\rfileSizeBytes\x12\x1b\n" +
	"\tfile_type\x18\x04 \x01(\tR\bfileType\x12\x1f\n" +
	"\vhash_sha256\x18\x05 \x01(\tR\n" +
	"hashSha256\"\xdd\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\rcontestant_id\x18\x02 \x01(\tR\fcontestantId\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12*\n" +
	"\x11agent_binary_hash\x18\x04 \x01(\tR\x0fagentBinaryHash\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xe5\x01\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x02 \x01(\x05R\x18heartbeatIntervalSeconds\x128\n" +
	"\rconfig_update\x18\x03 \x01(\v2\x13.voight.AgentConfigR\fconfigUpdate\x124\n" +
	"\x16deploy_warning_payload\x18\x04 \x01(\bR\x14deployWarningPayload\"\xc4\x02\n" +
	"\vAgentConfig\x12A\n" +
	"\x1dprocess_scan_interval_seconds\x18\x01 \x01(\x05R\x1aprocessScanIntervalSeconds\x12A\n" +
	"\x1dnetwork_scan_interval_seconds\x18\x02 \x01(\x05R\x1anetworkScanIntervalSeconds\x12C\n" +
	"\x1eresource_scan_interval_seconds\x18\x03 \x01(\x05R\x1bresourceScanIntervalSeconds\x122\n" +
	"\x15additional_ai_domains\x18\x04 \x03(\tR\x13additionalAiDomains\x126\n" +
	"\x17additional_ai_processes\x18\x05 \x03(\tR\x15additionalAiProcesses2\x98\x01\n" +
	"\x10TelemetryService\x12B\n" +
	"\x0fStreamTelemetry\x12\x17.voight.TelemetryReport\x1a\x14.voight.TelemetryAck(\x01\x12@\n" +
	"\tHeartbeat\x12\x18.voight.HeartbeatRequest\x1a\x19.voight.HeartbeatResponseB-Z+github.com/lockon/voight-agent/proto/voightb\x06proto3"

var (
	file_voight_telemetry_proto_rawDescOnce sync.Once
	file_voight_telemetry_proto_rawDescData []byte
)

func file_voight_telemetry_proto_rawDescGZIP() []byte {
	file_voight_telemetry_proto_rawDescOnce.Do(func() {
		file_voight_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_voight_telemetry_proto_rawDesc), len(file_voight_telemetry_proto_rawDesc)))
	})
	return file_voight_telemetry_proto_rawDescData
}

var file_voight_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_voight_telemetry_proto_goTypes = []any{
	(*TelemetryReport)(nil),       // 0: voight.TelemetryReport
	(*TelemetryAck)(nil),          // 1: voight.TelemetryAck
	(*ProcessSnapshot)(nil),       // 2: voight.ProcessSnapshot
	(*ProcessInfo)(nil),           // 3: voight.ProcessInfo
	(*NetworkEvent)(nil),          // 4: voight.NetworkEvent
	(*ResourceSnapshot)(nil),      // 5: voight.ResourceSnapshot
	(*FileAlert)(nil),             // 6: voight.FileAlert
	(*HeartbeatRequest)(nil),      // 7: voight.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 8: voight.HeartbeatResponse
	(*AgentConfig)(nil),           // 9: voight.AgentConfig
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_voight_telemetry_proto_depIdxs = []int32{
	10, // 0: voight.TelemetryReport.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 1: voight.TelemetryReport.process_snapshot:type_name -> voight.ProcessSnapshot
	4,  // 2: voight.TelemetryReport.network_event:type_name -> voight.NetworkEvent
	5,  // 3: voight.TelemetryReport.resource_snapshot:type_name -> voight.ResourceSnapshot
	6,  // 4: voight.TelemetryReport.file_alert:type_name -> voight.FileAlert
	3,  // 5: voight.ProcessSnapshot.processes:type_name -> voight.ProcessInfo
	10, // 6: voight.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 7: voight.HeartbeatResponse.config_update:type_name -> voight.AgentConfig
	0,  // 8: voight.TelemetryService.StreamTelemetry:input_type -> voight.TelemetryReport
	7,  // 9: voight.TelemetryService.Heartbeat:input_type -> voight.HeartbeatRequest
	1,  // 10: voight.TelemetryService.StreamTelemetry:output_type -> voight.TelemetryAck
	8,  // 11: voight.TelemetryService.Heartbeat:output_type -> voight.HeartbeatResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_voight_telemetry_proto_init() }
func file_voight_telemetry_proto_init() {
	if File_voight_telemetry_proto != nil {
		return
	}
	file_voight_telemetry_proto_msgTypes[0].OneofWrappers = []any{
		(*TelemetryReport_ProcessSnapshot)(nil),
		(*TelemetryReport_NetworkEvent)(nil),
		(*TelemetryReport_ResourceSnapshot)(nil),
		(*TelemetryReport_FileAlert)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_voight_telemetry_proto_rawDesc), len(file_voight_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_voight_telemetry_proto_goTypes,
		DependencyIndexes: file_voight_telemetry_proto_depIdxs,
		MessageInfos:      file_voight_telemetry_proto_msgTypes,
	}.Build()
	File_voight_telemetry_proto = out.File
	file_voight_telemetry_proto_goTypes = nil
	file_voight_telemetry_proto_depIdxs = nil
}
